name      = "client_dev"

data_dir  = "/data"

bind_addr = "0.0.0.0" # the default

server {
  enabled          = true
  bootstrap_expect = 1
}

client {
  enabled       = true
  node_pool = "dev"
  host_volume "scratchdir" {
      path      = "/tmp/nomad/nomad_temp/scratchdir"
      read_only = false
  }
}

acl {
  enabled = true
}

plugin "exec" {
    enabled = true
}

plugin "docker" {
  config {
   allow_privileged = true
   volumes {
     enabled = true
   }
   gc {
     image = false
     image_delay = "1h"
   }
  }
}
