== Introduction

The aim of this plugin is to integrate `Nextflow` and Hashicorp `Nomad` executor for batch processing of jobs.

The plugin itself is similar in design and scope to other executor integrations such as `nf-azure` and `k8s`, however as `Nomad` (arguably) offers a simpler setup, we aimed to address the usability of a Nomad cluster within the Nextflow ecosystem.

Hope you enjoy using the plugin and please participate in the development/feedback of the plugin in the `platform-nomad` channel on the Nextflow Slack instance. We would love to hear your feedback!



==== Some resources for familiarizing yourself with Nomad:

- https://developer.hashicorp.com/nomad/docs?product_intent=nomad[Hashicorp Documentation website for Nomad]

- https://developer.hashicorp.com/nomad/docs/configuration[Nomad Client/Server Configuration]

- https://developer.hashicorp.com/nomad/docs/job-specification[Nomad Job Specification]

- https://developer.hashicorp.com/nomad/docs/other-specifications/volume[Nomad Volumes specification]

- https://developer.hashicorp.com/nomad/docs/runtime[Nomad Runtime]

- https://developer.hashicorp.com/nomad/docs/drivers/docker[Task Driver - Docker]

- https://developer.hashicorp.com/nomad/plugins/drivers/podman[Task Driver - Podman]

- https://developer.hashicorp.com/nomad/docs/drivers/exec[Task Driver Isolated Fork/Exec ]

